server:
  port: ${PORT:50101} #服务端口
spring:
  application:
    name: xc-govern-center #指定服务名
eureka:
  client:
    registerWithEureka: false #服务注册开关，开发环境单机关闭
    fetchRegistry: false #服务发现开关，开发环境单机关闭
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
#      defaultZone: ${EUREKA_SERVER:http://eureka01:50101/eureka/, http://eureka02:50102/eureka/}
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01}